language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

sudo: false
env:
  JWT_SECRET: hgfhjgkhfvhjgcghchg
  TEST_MONGO_URI: "mongodb://localhost:27017/premier-league-test"
  global:
    - NODE_ENV=test
install:
  - npm install

  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3

script:
  - mongo --eval 'db.hostInfo()'
  - npm test

after_success:
  - npm run coveralls